config/routes.rb
Xamsa::Application.routes.draw do
  devise_for :players

  root 'home#index'

  resources :games do
    collection do 
      post :answer
    end
  end

  get 'live/play', to: 'live#play', as: :live_play

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :text

  belongs_to :question

  def check(submitted_answer)
    similarity = $white.similarity text, submitted_answer
    similarity >= 0.6
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  include AASM

  belongs_to :player1
  belongs_to :player2
  belongs_to :player3
  belongs_to :player4
  belongs_to :question_pack

  aasm do
    state :pending, initial: true, before_enter: :initialize_game
  end

  def initialize_game
    self.player1_score = 0
    self.player2_score = 0
    self.player3_score = 0
    self.player4_score = 0
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :full_name, :birthday, :sex, presence: true

  validates :terms_of_service, acceptance: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :text
  validates_presence_of :order
  validates_presence_of :question_pack

  validates_inclusion_of :order, in: 1..5
  validates_uniqueness_of :order, scope: :question_pack_id

  belongs_to :question_pack
  has_one :answer, dependent: :destroy
end

app/models/question_pack.rb
class QuestionPack < ActiveRecord::Base
  validates_presence_of :title

  has_many :questions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name
    devise_parameter_sanitizer.for(:sign_up) << :birthday
    devise_parameter_sanitizer.for(:sign_up) << :sex
  end

  def after_sign_in_path_for(resource)
    games_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_player!

  def index
  end

  def new
    @question_packs = QuestionPack.limit(5).order("RANDOM()")
    #below line calls 2 queries, but performs quicker than above
    #@question_packs = QuestionPack.where(id: QuestionPack.pluck(:id).shuffle[0..4])
    session[:score] ||= 0
  end

  def create
    session[:question_pack_id] = params[:question_pack]
    session[:question_order] = 0

    redirect_to game_path(:play)
  end

  def show
    if session[:question_order] > 4 || session[:question_order].nil?
      redirect_to new_game_path
    else
      session[:question_order] += 1
      @question_pack = QuestionPack.find_by_id(session[:question_pack_id])
      @question_word_count = @question_pack.questions.where(order: session[:question_order]).first.text.split.count
    end
  end

  def answer
    answer = QuestionPack.find_by_id(session[:question_pack_id]).questions.where(order: session[:question_order]).first.answer

    result = answer.check params[:answer]
    
    if result
      flash[:result] = 'Cavab doğrudur!'
      session[:score] += session[:question_order].to_i * 100
    else
      flash[:result] = "Cavab səhvdir! Düzgün cavab: #{answer.text}"
      session[:score] -= session[:question_order].to_i * 100
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_player
      redirect_to games_path
    end
  end
end

app/controllers/live_controller.rb
class LiveController < ApplicationController
  include ActionController::Live
  before_filter :authenticate_player!

  def play
    begin
      question = QuestionPack.find_by_id(session[:question_pack_id]).questions.where(order: session[:question_order]).first
      
      response.headers['Content-Type'] = 'text/event-stream; charset=utf-8'
      
      question.text.each_char do |char|
        response.stream.write message('game.char', { char: char })
        sleep 0.04
      end
      response.stream.write message('game.questionEnd')
    rescue IOError
    ensure
      response.stream.close
    end
  end

  private
  def message(event, data={})
    "event: #{event}\ndata: #{data.to_json}\n\n"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.slim
- if defined?(object) and object.errors.any?
  div class="alert alert-warning alert-dismissable"
    ul
    - object.errors.full_messages.each do |message|
      li= message

app/views/application/_flash_messages.html.slim
- if flash.count > 0
  div class="alert alert-info alert-dismissable"
    ul
    - flash.each do |key, value|
      li id="flash_#{key}"
        = value

app/views/application/_navbar.html.slim
nav class="navbar navbar-default navbar-static-top" role="navigation"
  .container
    a class="navbar-brand" href="#{player_signed_in? ? games_path : root_path}"
      = image_tag "favicon.png"
      = "Xəmsə"

    .pull-right.navbar-right
      - if player_signed_in?
        = link_to 'Çıxış', destroy_player_session_path, method: :delete
      - else
        = link_to 'Giriş', new_player_session_path

app/views/games/index.html.slim
.well-lg.text-center
  = link_to 'Oyuna başla', new_game_path, class: 'btn btn-primary btn-lg'

app/views/games/new.html.slim
.row
  .col-md-3.col-md-offset-9
    #score-box= "Sizin #{session[:score]} xalınız var"
.row
  .col-md-9.col-md-offset-3
    ul#question_packs
      = form_tag games_path, method: :post
        - @question_packs.each do |question_pack|
          li
            span class="glyphicon glyphicon-ban-circle"
            = question_pack.title
            = hidden_field_tag 'question_pack', question_pack.id

app/views/games/show.html.slim
#play
  h2= @question_pack.title
  .row
    .col-md-3.col-md-offset-9
      #score-box= "Sizin #{session[:score]} xalınız var"
  .row
    #question.question= "#{session[:question_order]}. "

  .row
    .answer-bar-wrapper.col-md-12
      .col-md-10.col-md-offset-1
        .answer-bar
          .red-bar
            .green-bar
          .timeout
            i class="glyphicon glyphicon-time"
            span= @question_word_count + 5
            = ' san'
          = form_tag answer_games_path, method: :post, remote: true
            =text_field_tag :answer, nil, id: 'answer-input', class: 'answer form-control input-lg'
          = button_tag '', type: 'button', id: 'stop-button', class: 'answer-button'

app/views/home/index.html.slim
.welcome-logo
div class="well-lg text-center"
  = link_to 'Giriş', new_player_session_path, class: 'btn btn-primary btn-lg'
  = link_to 'Qeydiyyat', new_player_registration_path, class: 'btn btn-primary btn-lg'
  = link_to 'Oyun qaydaları', '#', class: 'btn btn-primary btn-lg'

app/views/layouts/application.html.slim
doctype 5
html
  head
    meta charset="utf-8" 
    meta name="keywords" content="" 
    meta name="description" content=""
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = favicon_link_tag 'favicon.png'

    title= yield(:title) + "Xəmsə Milli İntellektual oyunu"

    link href="/favicon.ico" rel=("shortcut icon") 
    = yield(:header_tags)

    = stylesheet_link_tag "application", :type => nil, :media => "all"
    = javascript_include_tag "application", :type => nil, "data-turbolinks-track" => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body id=controller.controller_name 
    == render 'navbar'
    .container#main-container
      .main
        == render 'error_messages'
        == render 'flash_messages'
        = yield

app/views/players/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>